### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $wsdl ]] in class SoapClient

### ISSUE THREAD

**Issue by Mopster** [czim/laravel-service#3]
I'm getting the following exception after upgrading to Laravel 5.4.
Any idea where the problem might be ?
```
CouldNotConnectException in SoapService.php line 289:
Unresolvable dependency resolving [Parameter #0 [ <required> $wsdl ]] in class SoapClient


in SoapService.php line 289
at SoapService->initializeClient() in SoapService.php line 249
at SoapService->before() in AbstractService.php line 278
at AbstractService->call('processMessage', object(ServiceSoapRequest))
```

**Comment by nurikabe** [comment]
Looks like soap is defining a type that can't be found / instantiated.

**Comment by nurikabe** [comment]
Did the soap client get upgraded?  If so, can you force a downgrade?

**Comment by Mopster** [comment]
soap client did not get upgraded. Problem exists with both 0.9.28 and 0.9.30, and soap-client 0.2.6

**Comment by czim** [comment]
Just pushed a new version `0.9.31` that has been tested with, and should work with Laravel 5.4.

This problem occurred due to the [removal of container make() constructor parameters in 5.4](https://github.com/laravel/internals/issues/391#issuecomment-284579230), for which this version contains a work-around.

Note that you'll need to load the `ServiceServiceProvider` in your `config/app.php`, if you hadn't already.
